@startuml
title 0xb89adc24b12077a794a25c1012a0e993950551521b253f2087847d9e0b291e7a

caption mainnet, block 4, Fri, 25 Aug 2023 01:52:30 GMT
actor "0xf39f..2266" as f39f2266 
participant "0xcf7e..0fc9" as cf7e0fc9 <<PoolModifyPositionTest>>
participant "0x9fe4..a6e0" as 9fe4a6e0 <<PoolManager>>
participant "0x3cfe..9fee" as 3cfe9fee <<DynamicFeeHook>>
participant "0x5fbd..0aa3" as 5fbd0aa3 <<TestERC20>>
participant "0xe7f1..0512" as e7f10512 <<TestERC20>>

f39f2266 -> cf7e0fc9: modifyPosition(\n  key,\n  params)
activate cf7e0fc9
cf7e0fc9 -> 9fe4a6e0: lock(\n  data)
activate 9fe4a6e0
9fe4a6e0 -> cf7e0fc9: lockAcquired(\n  rawData)
activate cf7e0fc9
cf7e0fc9 -> 9fe4a6e0: modifyPosition(\n  key,\n  params)
activate 9fe4a6e0
9fe4a6e0 -> 3cfe9fee: beforeModifyPosition(\n  sender,\n  key,\n  params)
activate 3cfe9fee
return selector
9fe4a6e0 -> 3cfe9fee: afterModifyPosition(\n  sender,\n  key,\n  params,\n  delta)
activate 3cfe9fee
return selector
return delta
cf7e0fc9 -> 5fbd0aa3: transferFrom(\n  sender,\n  recipient,\n  amount)
activate 5fbd0aa3
return ?
cf7e0fc9 -> 9fe4a6e0: settle(\n  currency)
activate 9fe4a6e0
9fe4a6e0 -> 5fbd0aa3: balanceOf(\n  ?)
activate 5fbd0aa3
return ?
return paid
cf7e0fc9 -> e7f10512: transferFrom(\n  sender,\n  recipient,\n  amount)
activate e7f10512
return ?
cf7e0fc9 -> 9fe4a6e0: settle(\n  currency)
activate 9fe4a6e0
9fe4a6e0 -> e7f10512: balanceOf(\n  ?)
activate e7f10512
return ?
return paid
return ?
return result
return delta

note over 9fe4a6e0 #aqua
ModifyPosition:
  id,
  sender,
  tickLower,
  tickUpper,
  liquidityDelta
end note

/ note over 5fbd0aa3 #aqua
Transfer:
  from,
  to,
  value
end note

/ note over e7f10512 #aqua
Transfer:
  from,
  to,
  value
end note

@endumls